// generated by go run genicons.go; DO NOT EDIT

package icons

var list = []struct {
	name string
	data []byte
}{
	{"AddressBook", AddressBook},
	{"Balance", Balance},
	{"Blocks", Blocks},
	{"Copy", Copy},
	{"Help", Help},
	{"History", History},
	{"Info", Info},
	{"Light", Light},
	{"Link", Link},
	{"LinkOff", LinkOff},
	{"Loading", Loading},
	{"NoLight", NoLight},
	{"Ok", Ok},
	{"Overview", Overview},
	{"ParallelCoin", ParallelCoin},
	{"ParallelCoinRound", ParallelCoinRound},
	{"Peers", Peers},
	{"Receive", Receive},
	{"Received", Received},
	{"Search", Search},
	{"Send", Send},
	{"Sent", Sent},
	{"Settings", Settings},
	{"TxNumber", TxNumber},
	{"Unconfirmed", Unconfirmed},
}
